@startuml

title gameStart funからgamefinish funまでのシーケンス

participant gameStart #Red
participant gameLoop
participant main
participant mainAsync
participant monoCreated
participant monoFallOneSquare
participant monoMoveHorizontal
participant monoRotate
participant isCollision
participant isLineOver
participant isLinePlaced
participant gamePause
participant gamefinish #Red

gameStart -> gameLoop : スタートしたらgameLoop関数に行く

group ループし続ける
    gameLoop -> main : loopスタート

    main -> monoCreated : monoをフィールドに投下
    main -> monoFallOneSquare : monoを1マス下げる

    group 非同期処理
        mainAsync -> monoMoveHorizontal : monoを横に移動させる
        mainAsync -> monoRotate : monoを回転させる

        mainAsync -> gamePause : ポーズ処理
    end

    main -> isCollision : 接地判定
    main -> isLineOver : ゲームオーバー判定
    isLineOver -> gamefinish : ライン超えてるならfinish
    main -> isLinePlaced : ライン揃ってるか判定

    'ポーズ処理もあり、分岐が多いので
    'シーケンス図より状態遷移図の方が良い

    main -> gameLoop : もう一回ループ
end

gameLoop -> gamefinish : game

@enduml